version: '3.9'
services:
  rss2discord:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./config.yaml:/etc/rss2discord/config.yaml
    environment:
      RSS2DISCORD_DATABASE: postgres://rss2discord:rss2discord@postgres/rss2discord
      RSS2DISCORD_LOG: debug
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rss2discord
      POSTGRES_PASSWORD: rss2discord
      POSTGRES_DB: rss2discord
volumes:
  pgdata: